name: Check Community Health Files

on:
  repository:
    types: [created] 
  schedule:
    - cron: "0 0 * * *" 

jobs:
  check-health-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout compliance repo
        uses: actions/checkout@v3

      - name: Verify required files
        env:
          GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
        run: |
          REPO="${{ github.event.repository.full_name }}"
          echo "Checking repository: $REPO"

          REQUIRED_FILES=("README.md" "CONTRIBUTING.md" "CODE_OF_CONDUCT.md" "SECURITY.md" "SUPPORT.md")

          missing_files=()

          for file in "${REQUIRED_FILES[@]}"; do
            status=$(gh api repos/$REPO/contents/$file --silent || echo "404")
            if [[ "$status" == "404" ]]; then
              missing_files+=("$file")
            fi
          done

          if [ ${#missing_files[@]} -ne 0 ]; then
            echo "Missing files in $REPO: ${missing_files[*]}"

            gh api -X PATCH repos/$REPO -f archived=true

            exit 1
          else
            echo "All required health files are present."
          fi
