name: Enforce Community Health Files

on:
  schedule:
    - cron: "0 1 * * *"  # Run nightly
  workflow_dispatch:

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.ORG_ADMIN_TOKEN }}" | gh auth login --with-token

      - name: Get all repos in org
        run: |
          gh repo list my-org --json nameWithOwner -q '.[].nameWithOwner' > repos.txt

      - name: Check required files
        run: |
          set -x
          REQUIRED_FILES=("README.md" "CONTRIBUTING.md" "CODE_OF_CONDUCT.md" "SECURITY.md")

          while read repo; do
            echo "Checking $repo..."
            missing=()
            for file in "${REQUIRED_FILES[@]}"; do
              gh api repos/$repo/contents/$file >/dev/null 2>&1 || missing+=("$file")
            done

            if [ ${#missing[@]} -ne 0 ]; then
              echo "$repo missing: ${missing[*]}"
              gh api -X PATCH repos/$repo -f archived=true
              gh issue create --repo $repo \
                --title "Missing Community Health Files" \
                --body "This repository is missing: ${missing[*]}"
            else
              echo "$repo is compliant"
            fi
          done < repos.txt
